allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
peerDependencyRules:
  allowAny:
    - react
    - react-dom
minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@1.69.0 || 1.81.0'
  - '@oxlint/binding-android-arm64@1.69.0 || 1.81.0'
  - '@oxlint/binding-darwin-arm64@1.69.0 || 1.81.0'
  - '@oxlint/binding-darwin-x64@1.69.0 || 1.81.0'
  - '@oxlint/binding-freebsd-x64@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-arm64-gnu@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-arm64-musl@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-riscv64-musl@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-s390x-gnu@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-x64-gnu@1.69.0 || 1.81.0'
  - '@oxlint/binding-linux-x64-musl@1.69.0 || 1.81.0'
  - '@oxlint/binding-openharmony-arm64@1.69.0 || 1.81.0'
  - '@oxlint/binding-win32-arm64-msvc@1.69.0 || 1.81.0'
  - '@oxlint/binding-win32-ia32-msvc@1.69.0 || 1.81.0'
  - '@oxlint/binding-win32-x64-msvc@1.69.0 || 1.81.0'
  - oxlint@1.69.0 || 1.81.0
  - sanity-plugin-documents-pane@4.0.0
  - '@portabletext/editor@8.1.1'
  - '@portabletext/plugin-character-pair-decorator@9.0.5'
  - '@portabletext/plugin-dnd@2.0.5'
  - '@portabletext/plugin-input-rule@7.0.5'
  - '@portabletext/plugin-list-index@2.0.5'
  - '@portabletext/plugin-markdown-shortcuts@9.0.5'
  - '@portabletext/plugin-one-line@8.0.5'
  - '@portabletext/plugin-paste-link@5.0.5'
  - '@portabletext/plugin-table@2.0.5'
  - '@portabletext/plugin-typography@9.0.5'
  - '@sanity/access-ui@6.12.0 || 6.13.0'
  - '@sanity/cli-build@6.2.0'
  - '@sanity/cli-core@3.6.0'
  - '@sanity/cli@8.7.0'
  - '@sanity/diff@6.12.0 || 6.13.0'
  - '@sanity/mutator@6.12.0 || 6.13.0'
  - '@sanity/schema@6.12.0 || 6.13.0'
  - '@sanity/types@6.12.0 || 6.13.0'
  - '@sanity/util@6.12.0 || 6.13.0'
  - '@sanity/validation@6.12.0 || 6.13.0'
  - '@sanity/vision@6.12.0 || 6.13.0'
  - '@sanity/workbench-cli@2.3.0'
  - '@types/node@26.4.1'
  - i18next@26.4.1
  - lucide-react@1.39.0 || 1.43.0
  - next-sanity@13.3.4
  - react-i18next@17.0.13
  - sanity@6.12.0 || 6.13.0
  - '@sanity/client@8.6.1'
  - '@sanity/ui@4.2.0'
  - get-it@9.5.4
