# fly.toml app configuration file generated for bakdel-event-forwarder on 2025-02-05T21:53:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bakdel-event-forwarder'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  APP_ORIGIN = "https://www.bakdel.no"
  SANITY_DATASET = "production"
